// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SmartWatch

#ifndef _SMARTWATCH_UI_H
#define _SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
void ui_event_MainArcMenu(lv_event_t * e);
extern lv_obj_t * ui_MainArcMenu;
extern lv_obj_t * ui_MainSpinner;
extern lv_obj_t * ui_WiFiLabel;
extern lv_obj_t * ui_BTLabel;
extern lv_obj_t * ui_screenselectlabel;
extern lv_obj_t * ui_WeatherImage;
extern lv_obj_t * ui_WeatherLabel;
extern lv_obj_t * ui_MainSpinnerOuter;
extern lv_obj_t * ui_BatteryArc;
extern lv_obj_t * img_glow;
extern lv_obj_t * img_bell;

// SCREEN: ui_ClockScreen
void ui_ClockScreen_screen_init(void);
extern lv_obj_t * ui_ClockScreen;
extern void update_main_screen(void);
void ui_event_MainArcClockMenu(lv_event_t * e);
extern lv_obj_t * ui_MainArcClockMenu;
extern lv_obj_t *hour_hand_img;
extern lv_obj_t *minute_hand_img;
extern lv_obj_t *second_hand_img;


// SCREEN: ui_MusicControls
void ui_MusicControls_screen_init(void);
extern lv_obj_t * ui_MusicControls;
void ui_event_MainArcMenuMusic(lv_event_t * e);
extern lv_obj_t * ui_MainArcMenuMusic;
extern lv_obj_t * ui_musicartwork;
extern lv_obj_t * ui_SongTitleLabel;
extern lv_obj_t * ui_ArtistLabel;
void ui_event_MusicArc(lv_event_t * e);
extern lv_obj_t * ui_MusicArc;
void ui_event_playbutton(lv_event_t * e);
extern lv_obj_t * ui_playbutton;
void ui_event_previousbutton(lv_event_t * e);
extern lv_obj_t * ui_previousbutton;
void ui_event_nextbutton(lv_event_t * e);
extern lv_obj_t * ui_nextbutton;
void ui_event_MusicVolume(lv_event_t * e);
extern lv_obj_t * ui_MusicVolume;
// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
extern lv_obj_t * ui_Settings;
void ui_event_MainArcSettingsMenu(lv_event_t * e);
extern lv_obj_t * ui_MainArcSettingsMenu;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(watch360);    // assets/watchface.png
LV_IMG_DECLARE(hour_hand);    // assets/hour_hand.png
LV_IMG_DECLARE(minute_hand);    // assets/minute_hand.png
LV_IMG_DECLARE(second_hand);    // assets/secondHand.png
LV_IMG_DECLARE(bell_icon); 



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
