// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SmartWatch

#include "ui.h"
#include <Arduino.h>

 void ui_ClockScreen_screen_init(void)
{
    ui_ClockScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ClockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Set background image and adjust for 360x360 display
    lv_obj_set_style_bg_img_src(ui_ClockScreen, &watch360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_size(ui_ClockScreen, 360, 360);  // Set to full screen size
    lv_obj_set_align(ui_ClockScreen, LV_ALIGN_CENTER);

    ui_MainArcClockMenu = lv_arc_create(ui_ClockScreen);
    lv_obj_set_width(ui_MainArcClockMenu, 210); // Adjusted for 360x360
    lv_obj_set_height(ui_MainArcClockMenu, 210);
    lv_obj_set_align(ui_MainArcClockMenu, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_MainArcClockMenu, 0, 500);
    lv_arc_set_value(ui_MainArcClockMenu, 200);
    lv_obj_set_style_arc_color(ui_MainArcClockMenu, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MainArcClockMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MainArcClockMenu, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MainArcClockMenu, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MainArcClockMenu, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MainArcClockMenu, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MainArcClockMenu, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MainArcClockMenu, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MainArcClockMenu, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainArcClockMenu, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

// Hour hand
    hour_hand_img = lv_img_create(ui_ClockScreen);
    lv_img_set_src(hour_hand_img, &hour_hand);
    lv_obj_set_width(hour_hand_img, LV_SIZE_CONTENT);
    lv_obj_set_height(hour_hand_img, LV_SIZE_CONTENT);
    lv_obj_align(hour_hand_img, LV_ALIGN_CENTER, 0, 0);
    lv_obj_add_flag(hour_hand_img, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(hour_hand_img, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_pivot(hour_hand_img, 20, 5); // Adjusted based on image reference

    // Minute hand
    minute_hand_img = lv_img_create(ui_ClockScreen);
    lv_img_set_src(minute_hand_img, &minute_hand);
    lv_obj_set_width(minute_hand_img, LV_SIZE_CONTENT);
    lv_obj_set_height(minute_hand_img, LV_SIZE_CONTENT);
    lv_obj_align(minute_hand_img, LV_ALIGN_CENTER, 0, 0);
    lv_obj_add_flag(minute_hand_img, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(minute_hand_img, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_pivot(minute_hand_img, 25, 5); // Adjusted based on image reference

    // Second hand
    second_hand_img = lv_img_create(ui_ClockScreen);
    lv_img_set_src(second_hand_img, &second_hand);
    lv_obj_set_width(second_hand_img, LV_SIZE_CONTENT);
    lv_obj_set_height(second_hand_img, LV_SIZE_CONTENT);
    lv_obj_align(second_hand_img, LV_ALIGN_CENTER, 0, 0);
    lv_obj_add_flag(second_hand_img, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(second_hand_img, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_pivot(second_hand_img, 15, 5); // Adjusted based on image reference

    lv_obj_add_event_cb(ui_MainArcClockMenu, ui_event_MainArcClockMenu, LV_EVENT_ALL, NULL);
} 

