// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SmartWatch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void mainarc_valuechange(lv_event_t * e);
void mainarc_select(lv_event_t * e);
void mainarcclock_valuechange(lv_event_t * e);
void mainarcclock_select(lv_event_t * e);
void mainarcmusic_valuechange(lv_event_t * e);
void mainarcmusic_select(lv_event_t * e);
void musictrack_release(lv_event_t * e);
void playbutton_pressed(lv_event_t * e);
void prevbutton_pressed(lv_event_t * e);
void nextbutton_pressed(lv_event_t * e);
void mainarcsettings_valuechange(lv_event_t * e);
void mainarcsettings_select(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
