// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SmartWatch

#include "ui.h"
#include <Arduino.h>

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x01070f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_MainScreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    



      // Initialize the main arc menu with glow effect on the indicator
    ui_MainArcMenu = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_MainArcMenu, 200);
    lv_obj_set_height(ui_MainArcMenu, 200);
    lv_obj_set_align(ui_MainArcMenu, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_MainArcMenu, 0, 500);
    lv_arc_set_value(ui_MainArcMenu, 100);
    lv_obj_set_style_arc_width(ui_MainArcMenu, 10, LV_PART_MAIN);
    
    lv_obj_set_style_arc_color(ui_MainArcMenu, lv_color_hex(0x01070f), LV_PART_MAIN);
    lv_obj_set_style_arc_color(ui_MainArcMenu, lv_color_hex(0x79CBFC), LV_PART_INDICATOR);

    //lv_obj_set_style_bg_color(ui_MainArcMenu, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
   // lv_obj_set_style_bg_opa(ui_MainArcMenu, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_remove_style(ui_MainArcMenu, NULL, LV_PART_KNOB); // Remove knob
     lv_obj_set_style_arc_width(ui_MainArcMenu, 10, LV_PART_INDICATOR);
    lv_obj_set_style_arc_rounded(ui_MainArcMenu, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MainArcMenu, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
   
    // Main arc style
    static lv_style_t style_main_arc;
    lv_style_init(&style_main_arc);
    //lv_style_set_arc_color(&style_main_arc, lv_color_hex(0x141721));
    lv_style_set_arc_color(&style_main_arc, lv_color_hex(0x01070f) );
    lv_style_set_arc_opa(&style_main_arc, 255);
    lv_style_set_arc_rounded(&style_main_arc, false); // Ensuring no rounded ends for main arc

    // Indicator arc style with a more intense glow effect
    static lv_style_t style_indicator_glow;
    lv_style_init(&style_indicator_glow);
    lv_style_set_arc_color(&style_indicator_glow, lv_color_hex(0x79CBFC));
    lv_style_set_arc_opa(&style_indicator_glow, 255);
    lv_style_set_arc_width(&style_indicator_glow, 10); // Increased width for visibility
    lv_style_set_arc_rounded(&style_indicator_glow, false); // Ensuring no rounded ends for indicator

    // Enhanced glow effect settings
    //lv_style_set_shadow_color(&style_indicator_glow, lv_color_hex(0x00d5ff));  // Bright cyan glow color
    //lv_style_set_shadow_opa(&style_indicator_glow, 100);  // Full opacity for maximum glow
    //lv_style_set_shadow_width(&style_indicator_glow, 20);  // Increased width to extend glow
    //lv_style_set_shadow_spread(&style_indicator_glow, 10);  // Increased spread for more visible glow
    //lv_style_set_blend_mode(&style_indicator_glow, LV_BLEND_MODE_ADDITIVE);


    // Apply the styles to the arc
    lv_obj_add_style(ui_MainArcMenu, &style_main_arc, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_MainArcMenu, &style_indicator_glow, LV_PART_INDICATOR | LV_STATE_DEFAULT | LV_STATE_PRESSED);




    // Create the spinner with glow effect on the indicator
    ui_MainSpinnerOuter = lv_spinner_create(ui_MainScreen);
     
    lv_obj_set_width(ui_MainSpinnerOuter, 210);
    lv_obj_set_height(ui_MainSpinnerOuter, 210);
    lv_obj_set_align(ui_MainSpinnerOuter, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainSpinnerOuter, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_spinner_set_anim_params(ui_MainSpinnerOuter, 1000, 90);
    //lv_obj_set_style_blend_mode(ui_MainSpinnerOuter, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);



    // Spinner main arc style (background arc)
    static lv_style_t style_spinner_main_arc;
    lv_style_init(&style_spinner_main_arc);
    lv_style_set_arc_color(&style_spinner_main_arc, lv_color_hex(0x161720));
    lv_style_set_arc_opa(&style_spinner_main_arc, 255);
    lv_style_set_arc_width(&style_spinner_main_arc, 2);

    // Apply the same glow style to the spinner's indicator arc
    lv_obj_add_style(ui_MainSpinnerOuter, &style_spinner_main_arc, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_MainSpinnerOuter, &style_indicator_glow, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Apply style for the indicator arc color and width (overrides arc color in style_indicator_glow)
    lv_obj_set_style_arc_color(ui_MainSpinnerOuter, lv_color_hex(0x2C9FFD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MainSpinnerOuter, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MainSpinnerOuter, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    

/* 
    ui_MainSpinner = lv_spinner_create(ui_MainScreen, 1000, 90);
    lv_obj_set_width(ui_MainSpinner, 170);
    lv_obj_set_height(ui_MainSpinner, 170);
    lv_obj_set_align(ui_MainSpinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_MainSpinner, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_MainSpinner, lv_color_hex(0x161720), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MainSpinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MainSpinner, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MainSpinner, lv_color_hex(0x81F0FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MainSpinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MainSpinner, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT); */

    // Replace ui_MainSpinner with ui_BatteryArc

ui_BatteryArc = lv_arc_create(ui_MainScreen);
lv_obj_set_size(ui_BatteryArc, 170, 170);
lv_obj_align(ui_BatteryArc, LV_ALIGN_CENTER, 0, 0);
lv_arc_set_bg_angles(ui_BatteryArc, 0, 360);
lv_arc_set_rotation(ui_BatteryArc, 270); // Start from top
lv_arc_set_value(ui_BatteryArc, 100); // Initially 100%
lv_obj_remove_style(ui_BatteryArc, NULL, LV_PART_KNOB); // Remove knob
lv_obj_clear_flag(ui_BatteryArc, LV_OBJ_FLAG_CLICKABLE); // Non-clickable

// Set initial style
lv_obj_set_style_arc_width(ui_BatteryArc, 5, LV_PART_MAIN);
lv_obj_set_style_arc_width(ui_BatteryArc, 5, LV_PART_INDICATOR);
lv_obj_set_style_arc_color(ui_BatteryArc, lv_color_hex(0x00FF00), LV_PART_INDICATOR); // Green color

    ui_WiFiLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_WiFiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiLabel, -35);
    lv_obj_set_y(ui_WiFiLabel, 50);
    lv_obj_set_align(ui_WiFiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiLabel, LV_SYMBOL_WIFI);
    lv_obj_set_style_text_color(ui_WiFiLabel, lv_color_hex(0x41C7FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WiFiLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WiFiLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BTLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTLabel, 35);
    lv_obj_set_y(ui_BTLabel, 50);
    lv_obj_set_align(ui_BTLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BTLabel, LV_SYMBOL_BLUETOOTH);
    lv_obj_set_style_text_color(ui_BTLabel, lv_color_hex(0x41C7FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BTLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BTLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screenselectlabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_screenselectlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_screenselectlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_screenselectlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_screenselectlabel, "Main");
    lv_obj_set_style_text_color(ui_screenselectlabel, lv_color_hex(0xFFAD00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_screenselectlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherImage = lv_img_create(ui_MainScreen);
    lv_obj_set_width(ui_WeatherImage, 32);
    lv_obj_set_height(ui_WeatherImage, 32);
    lv_obj_set_x(ui_WeatherImage, -20);
    lv_obj_set_y(ui_WeatherImage, -50);
    lv_obj_set_align(ui_WeatherImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WeatherImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_WeatherLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherLabel, 20);
    lv_obj_set_y(ui_WeatherLabel, -50);
    lv_obj_set_align(ui_WeatherLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherLabel, "?"); // needs to have the symbol °
    lv_obj_set_style_text_color(ui_WeatherLabel, lv_color_hex(0x41C7FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);


/*         //LV_IMG_DECLARE(img_watchface_glow_png);
    img_glow = lv_img_create(ui_MainScreen);
    lv_img_set_src(img_glow, "A:/lvgl/img/watchface_glow.png");
    lv_obj_set_width(img_glow, 240);
    lv_obj_set_height(img_glow, 240);
    lv_obj_align(img_glow, LV_ALIGN_CENTER, 0, 0); 

    //LV_IMG_DECLARE(img_watchface_glow_png);
    
     */



/*     img_bell = lv_img_create(ui_MainScreen);
    //lv_img_set_src(img_bell, &bell_icon);
    lv_img_set_src(img_bell, "A:/lvgl/img/bell_icon.png");
    lv_obj_set_width(img_bell, LV_SIZE_CONTENT);
    lv_obj_set_height(img_bell, LV_SIZE_CONTENT);
    lv_obj_set_x(img_bell, -25) ;
    lv_obj_set_y(img_bell, -100);
    lv_obj_set_align(img_bell, LV_ALIGN_CENTER); */

    lv_obj_add_event_cb(ui_MainArcMenu, ui_event_MainArcMenu, LV_EVENT_ALL, NULL);

       // Apply the styles to the arc
    //lv_obj_add_style(ui_MainArcMenu, &style_main_arc, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_add_style(ui_MainArcMenu, &style_indicator_glow, LV_PART_INDICATOR | LV_STATE_DEFAULT | LV_STATE_PRESSED);
}