// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SmartWatch

#include "ui.h"

void ui_MusicControls_screen_init(void)
{
    ui_MusicControls = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MusicControls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MusicControls, lv_color_hex(0x110824), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicControls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainArcMenuMusic = lv_arc_create(ui_MusicControls);
    lv_obj_set_width(ui_MainArcMenuMusic, 240);
    lv_obj_set_height(ui_MainArcMenuMusic, 240);
    lv_obj_set_align(ui_MainArcMenuMusic, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_MainArcMenuMusic, 0, 500);
    lv_arc_set_value(ui_MainArcMenuMusic, 100);
    lv_obj_set_style_arc_color(ui_MainArcMenuMusic, lv_color_hex(0x211E14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MainArcMenuMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MainArcMenuMusic, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MainArcMenuMusic, lv_color_hex(0xFFA70A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MainArcMenuMusic, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MainArcMenuMusic, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MainArcMenuMusic, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainArcMenuMusic, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_musicartwork = lv_img_create(ui_MusicControls);
    lv_obj_set_width(ui_musicartwork, 72);
    lv_obj_set_height(ui_musicartwork, 72);
    lv_obj_set_x(ui_musicartwork, 0);
    lv_obj_set_y(ui_musicartwork, -39);
    lv_obj_set_align(ui_musicartwork, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_musicartwork, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_musicartwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SongTitleLabel = lv_label_create(ui_MusicControls);
    lv_obj_set_width(ui_SongTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SongTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SongTitleLabel, 0);
    lv_obj_set_y(ui_SongTitleLabel, 8);
    lv_obj_set_align(ui_SongTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_SongTitleLabel, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_SongTitleLabel, "SongTitle, Artist");
    lv_obj_set_style_text_color(ui_SongTitleLabel, lv_color_hex(0xFFAE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SongTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SongTitleLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArtistLabel = lv_label_create(ui_MusicControls);
    lv_obj_set_width(ui_ArtistLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArtistLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArtistLabel, 0);
    lv_obj_set_y(ui_ArtistLabel, 22);
    lv_obj_set_align(ui_ArtistLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ArtistLabel, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_ArtistLabel, "SongTitle, Artist");
    lv_obj_set_style_text_color(ui_ArtistLabel, lv_color_hex(0x439BE0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArtistLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArtistLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicArc = lv_arc_create(ui_MusicControls);
    lv_obj_set_width(ui_MusicArc, 180);
    lv_obj_set_height(ui_MusicArc, 180);
    lv_obj_set_align(ui_MusicArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_MusicArc, 50);
    lv_arc_set_bg_angles(ui_MusicArc, 200, 340);
    lv_obj_set_style_arc_color(ui_MusicArc, lv_color_hex(0x101420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MusicArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MusicArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MusicArc, lv_color_hex(0x7BCAFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MusicArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MusicArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MusicArc, lv_color_hex(0xBAE2FC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MusicArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MusicArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MusicArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MusicArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_playbutton = lv_btn_create(ui_MusicControls);
    lv_obj_set_width(ui_playbutton, 32);
    lv_obj_set_height(ui_playbutton, 32);
    lv_obj_set_x(ui_playbutton, 0);
    lv_obj_set_y(ui_playbutton, 48);
    lv_obj_set_align(ui_playbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_playbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_playbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_playbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_playbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_playbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_playbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_playbutton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_playbutton, lv_color_hex(0x86B2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_playbutton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_previousbutton = lv_btn_create(ui_MusicControls);
    lv_obj_set_width(ui_previousbutton, 32);
    lv_obj_set_height(ui_previousbutton, 32);
    lv_obj_set_x(ui_previousbutton, -40);
    lv_obj_set_y(ui_previousbutton, 48);
    lv_obj_set_align(ui_previousbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_previousbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_previousbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_previousbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_previousbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_previousbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_previousbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_previousbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_previousbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_previousbutton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_previousbutton, lv_color_hex(0x86B2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_previousbutton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_nextbutton = lv_btn_create(ui_MusicControls);
    lv_obj_set_width(ui_nextbutton, 32);
    lv_obj_set_height(ui_nextbutton, 32);
    lv_obj_set_x(ui_nextbutton, 40);
    lv_obj_set_y(ui_nextbutton, 48);
    lv_obj_set_align(ui_nextbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nextbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_nextbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_nextbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nextbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_nextbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_nextbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_nextbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nextbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nextbutton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_nextbutton, lv_color_hex(0x86B2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_nextbutton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MusicVolume = lv_arc_create(ui_MusicControls);
    lv_obj_set_width(ui_MusicVolume, 190);
    lv_obj_set_height(ui_MusicVolume, 190);
    lv_obj_set_align(ui_MusicVolume, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_MusicVolume, LV_DIR_HOR);
    lv_arc_set_value(ui_MusicVolume, 50);
    lv_arc_set_bg_angles(ui_MusicVolume, 50, 130);
    lv_obj_set_style_arc_color(ui_MusicVolume, lv_color_hex(0x101420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MusicVolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MusicVolume, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MusicVolume, lv_color_hex(0x7BCAFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MusicVolume, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MusicVolume, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MusicVolume, lv_color_hex(0xCBE6FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicVolume, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MusicVolume, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MusicVolume, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MusicVolume, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MusicVolume, 3, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MainArcMenuMusic, ui_event_MainArcMenuMusic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MusicArc, ui_event_MusicArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_playbutton, ui_event_playbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_previousbutton, ui_event_previousbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_nextbutton, ui_event_nextbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MusicVolume, ui_event_MusicVolume, LV_EVENT_ALL, NULL);

}
